do
    local library = loadstring(game:HttpGet('https://raw.githubusercontent.com/actz2196/randomshit/main/UiLib.lua',true))()
    local w1 = library:KRNL_0bebcb447a7726(true)
    local wc1 = w1:KRNL_1d7cf31a6a3640('Main')
    --local wc2 = w1:KRNL_1d7cf31a6a3640('Teleports')
    --local wc3 = w1:KRNL_1d7cf31a6a3640('Teleports 2')
    local wc4 = w1:KRNL_1d7cf31a6a3640('Misc')
	local autobubble = false
	wc1:KRNL_cbb5ee2a24cf34('Auto-Bubble', false, function()
		autobubble = not autobubble
		while autobubble and game:GetService('RunService').Heartbeat:wait() do 
			game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BlowBubble", true)
		end
	end)
	local autosell = false
	wc1:KRNL_cbb5ee2a24cf34('Auto-Sell', false, function()
		autosell = not autosell
        while autosell and game:GetService('RunService').Heartbeat:wait() do
            if workspace:FindFirstChild('asfajsgkajg') then
                game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(4699.03076, 37.007885, -16052.2246)
            else
            local safe = Instance.new('Part',game.Workspace)
            safe.Size = Vector3.new(11.54, 0.88, 9.51)
            safe.Anchored = true
            safe.CFrame = CFrame.new(4698.21924, 33.5603638, -16052.751)
            safe.Name = ("asfajsgkajg")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("SellBubble","Mystic ForestSell")
            end
		end
    end)
    local autogum = false
    wc1:KRNL_cbb5ee2a24cf34('Auto-Gum', false, function()
        autogum = not autogum
        while autogum and game:GetService('RunService').Heartbeat:wait() do
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthGum","Gum","Stretchy Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthGum","Gum","Extra Stretchy Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthGum","Gum","Chewy Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthGum","Gum","Extra Chewy Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthGum","Gum","Epic Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthGum","Gum","Super Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthGum","Gum","Super Duper Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthGum","Gum","Omega Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthGum","Gum","Unreal Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthGum","Gum","Monster Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceGum","Gum","Heroic Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceGum","Gum","Legendary Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceGum","Gum","Mythical Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceGum","Gum","Godly Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceGum","Gum","Universal Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceGum","Gum","Alien Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceGum","Gum","Radioactive Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceGum","Gum","Experiment #32")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceGum","Gum","Experiment #54")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceGum","Gum","Heroic Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","CandyGum","Gum","Sugar Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","CandyGum","Gum","Sweet Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","CandyGum","Gum","Sour Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","BeachGum","Gum","Sandy Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","BeachGum","Gum","Fish Gum")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","BeachGum","Gum","Ocean Gum")
        end
    end)
    local autoflavor = false
    wc1:KRNL_cbb5ee2a24cf34('Auto-Flavors', false, function()
        autoflavor = not autoflavor
        while autoflavor and game:GetService('RunService').Heartbeat:wait() do
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthFlavors","Flavors","Blueberry")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthFlavors","Flavors","Pizza")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthFlavors","Flavors","Cherry")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthFlavors","Flavors","Donut")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthFlavors","Flavors","Chocolate")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthFlavors","Flavors","Watermelon")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthFlavors","Flavors","Contrast")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthFlavors","Flavors","Gold")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthFlavors","Flavors","Lemon")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","EarthFlavors","Flavors","Swirl")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Frost")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Ruby")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Void")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Aqua")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Plasma")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Lava")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Venom")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Galaxy")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Rainbow")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Surge")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","SpaceFlavors","Flavors","Triangular")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","CandyFlavors","Flavors","Popcorn")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","CandyFlavors","Flavors","Puzzle")
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("BuyShopItem","CandyFlavors","Flavors","Sprinkles")
        end
    end)
    --[[
    wc2:KRNL_2478d3ef4c426a("Overworld", Color3.new(255,255,255))
    wc2:KRNL_0234a044e17801('The Floating Island', function()
        if game.Workspace.Worlds:FindFirstChild('Overworld') then
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Floating Island")
        elseif game.Workspace.Worlds:FindFirstChild('Candy Land') then
           game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("Teleport","Candy LandSpawn")
           wait(0.3)
           game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-496.784851, 45.2773705, -2783.7522)
           wait(0.3)
           game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-489.111298, 45.4753952, -2768.51221)
           wait(2)
           game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Floating Island")
        elseif game.Workspace.Worlds:FindFirstChild('Toy Land') then
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("Teleport","Toy LandSpawn")
            wait(0.3)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-88.6398621, 45.2779579, -5085.91211)
            wait(3)
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Floating Island")
        elseif game.Workspace.Worlds:FindFirstChild('Beach World') then
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("Teleport","Beach WorldSpawn")
            wait(0.3)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(497.28891, 53.9588814, -8314.57715)
            wait(2)
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Floating Island")
        elseif game.Workspace.Worlds:FindFirstChild('Atlantis') then
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("Teleport", "AtlantisSpawn")
            wait(0.3)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(264.423553, 48.3545952, -12773.5273)
            wait(0.3)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(271.214691, 48.3545914, -12762.623)
            wait(0.1)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(274.720673, 48.354599, -12756.9492)
            wait(0.1)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(278.271057, 48.354599, -12751.1709)
            wait(2)
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Floating Island") 
        elseif game.Workspace.Worlds:FindFirstChild('Rainbow Land') then
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("Teleport","Rainbow LandSpawn")
            wait(0.1)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(1481.39392, 19.2867355, -17656.4551)
            wait(0.1)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(1486.37488, 19.2872448, -17649.9375)
            wait(2)
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Floating Island")
        elseif game.Workspace.Worlds:FindFirstChild('Underworld') then
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("Teleport","UnderworldSpawn")
            wait(0.3)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(2395.09082, 22.5811787, -20132.2031)
            wait(0.3)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(2412.0686, 22.5811825, -20131.0215)
            wait(2.5)
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Floating Island")
        elseif game.Workspace.Worlds:FindFirstChild('Mystic Forest') then
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("Teleport","Mystic ForestSpawn")
            wait(0.3)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(4814.16113, 43.2216759, -16144.6836)
            wait(0.3)
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(4819.75781, 43.2216759, -16154.0518)
            wait(2.5)
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Floating Island")
        end
    end)
    wc2:KRNL_0234a044e17801('Space Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Space")
    end)
    wc2:KRNL_0234a044e17801('Twilight Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Twilight")
    end)
    wc2:KRNL_0234a044e17801('The Skylands', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Skylands")
    end)
    wc2:KRNL_0234a044e17801('Gem Genie', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Zen")
    end)
    wc2:KRNL_0234a044e17801('The Void', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","The Void")
    end)
    wc2:KRNL_0234a044e17801('XP Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","XP Island")
    end)
    wc2:KRNL_2478d3ef4c426a("Candy Land", Color3.new(255,255,255))
    wc2:KRNL_0234a044e17801('Gumdrop Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Gumdrop Island")
    end)
    wc2:KRNL_0234a044e17801('Rewards Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Rewards Island")
    end)
    wc2:KRNL_0234a044e17801('Sugar Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Sugar Island")
    end)
    wc2:KRNL_0234a044e17801('Candy Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Candy Island")
    end)
    wc2:KRNL_0234a044e17801('Sweet Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Sweet Island")
    end)
    wc2:KRNL_2478d3ef4c426a("Toy Land", Color3.new(255,255,255))
    wc2:KRNL_0234a044e17801('Block Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Block Island")
    end)
    wc2:KRNL_0234a044e17801('Block Rewards', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Block Rewards")
    end)
    wc2:KRNL_0234a044e17801('Toy Isle', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Toy Isle")
    end)
    wc2:KRNL_0234a044e17801('Teddy Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Teddy Island")
    end)
    wc2:KRNL_0234a044e17801('Treasure Isle', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Treasure Isle")
    end)
    wc2:KRNL_2478d3ef4c426a("Beach World", Color3.new(255,255,255))
    wc2:KRNL_0234a044e17801('Sea Island',function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Sea Island")
    end)
    wc2:KRNL_0234a044e17801('Sea Rewards', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Sea Rewards")
    end)
    wc2:KRNL_0234a044e17801('Shell Isle', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Shell Isle")
    end)
    wc2:KRNL_0234a044e17801('Oceanic Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","TOceanic Island")
    end)
    wc2:KRNL_0234a044e17801('Sea Shell Isle', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Sea Shell Isle")
    end)
    wc3:KRNL_2478d3ef4c426a("Atlantis", Color3.new(255,255,255))
    wc3:KRNL_0234a044e17801('Water Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Water Island")
    end)
    wc3:KRNL_0234a044e17801('Atlantis Rewards', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Atlantis Rewards")
    end)
    wc3:KRNL_0234a044e17801('Atlantis Isle', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Atlantis Isle")
    end)
    wc3:KRNL_0234a044e17801('Treasure Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Treasure Island")
    end)
    wc3:KRNL_0234a044e17801('Sandy Island', function()
        game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("TeleportToCheckpoint","Sandy Island")
    end)
    ]]
    local cac = false
    wc4:KRNL_cbb5ee2a24cf34('Collect All Chests', false, function()
        cac = not cac
        while cac and game:GetService('RunService').Heartbeat:wait() do
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","The Floating Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","The Skylands")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","The Void")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","XP Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Gumdrop Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Candy Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Sweet Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Block Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Teddy Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Treasure Isle")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Sea Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Oceanic Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Sea Shell Isle")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Water Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Treasure Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Sandy Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Red Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Blue Island")
            game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer("CollectChestReward","Purple Island")
        end
    end)
    game.CoreGui["Krnl Hub"].Main.Top.Title.Text = "swaggy actz#2196 lol"
end
